//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/AckMessage.msg.
//

#ifndef __TASK_OFFLOADING_ACKMESSAGE_M_H
#define __TASK_OFFLOADING_ACKMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace task_offloading {

class AckMessage;

}  // namespace task_offloading

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace task_offloading {

/**
 * Class generated from <tt>app/messages/AckMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet AckMessage extends veins::BaseFrame1609_4
 * {
 *     int hostIndex;
 *     int taskID;
 *     int partitionID;
 * }
 * </pre>
 */
class AckMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int hostIndex = 0;
    int taskID = 0;
    int partitionID = 0;

  private:
    void copy(const AckMessage& other);

  protected:
    bool operator==(const AckMessage&) = delete;

  public:
    AckMessage(const char *name=nullptr, short kind=0);
    AckMessage(const AckMessage& other);
    virtual ~AckMessage();
    AckMessage& operator=(const AckMessage& other);
    virtual AckMessage *dup() const override {return new AckMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHostIndex() const;
    virtual void setHostIndex(int hostIndex);

    virtual int getTaskID() const;
    virtual void setTaskID(int taskID);

    virtual int getPartitionID() const;
    virtual void setPartitionID(int partitionID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckMessage& obj) {obj.parsimUnpack(b);}


}  // namespace task_offloading


namespace omnetpp {

template<> inline task_offloading::AckMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<task_offloading::AckMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASK_OFFLOADING_ACKMESSAGE_M_H

