//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/AckTimerMessage.msg.
//

#ifndef __TASK_OFFLOADING_ACKTIMERMESSAGE_M_H
#define __TASK_OFFLOADING_ACKTIMERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace task_offloading {

class AckTimerMessage;

}  // namespace task_offloading

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace task_offloading {

/**
 * Class generated from <tt>app/messages/AckTimerMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet AckTimerMessage extends veins::BaseFrame1609_4
 * {
 *     int hostIndex;
 *     double taskComputationTime;
 * }
 * </pre>
 */
class AckTimerMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int hostIndex = 0;
    double taskComputationTime = 0;

  private:
    void copy(const AckTimerMessage& other);

  protected:
    bool operator==(const AckTimerMessage&) = delete;

  public:
    AckTimerMessage(const char *name=nullptr, short kind=0);
    AckTimerMessage(const AckTimerMessage& other);
    virtual ~AckTimerMessage();
    AckTimerMessage& operator=(const AckTimerMessage& other);
    virtual AckTimerMessage *dup() const override {return new AckTimerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHostIndex() const;
    virtual void setHostIndex(int hostIndex);

    virtual double getTaskComputationTime() const;
    virtual void setTaskComputationTime(double taskComputationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckTimerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckTimerMessage& obj) {obj.parsimUnpack(b);}


}  // namespace task_offloading


namespace omnetpp {

template<> inline task_offloading::AckTimerMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<task_offloading::AckTimerMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASK_OFFLOADING_ACKTIMERMESSAGE_M_H

