//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/BeaconMessage.msg.
//

#ifndef __TASK_OFFLOADING_BEACONMESSAGE_M_H
#define __TASK_OFFLOADING_BEACONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace task_offloading {

class BeaconMessage;

}  // namespace task_offloading

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace task_offloading {

/**
 * Class generated from <tt>app/messages/BeaconMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet BeaconMessage extends veins::BaseFrame1609_4
 * {
 *     int hostID;
 *     veins::LAddress::L2Type senderAddress = -1;
 * }
 * </pre>
 */
class BeaconMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int hostID = 0;
    ::veins::LAddress::L2Type senderAddress = -1;

  private:
    void copy(const BeaconMessage& other);

  protected:
    bool operator==(const BeaconMessage&) = delete;

  public:
    BeaconMessage(const char *name=nullptr, short kind=0);
    BeaconMessage(const BeaconMessage& other);
    virtual ~BeaconMessage();
    BeaconMessage& operator=(const BeaconMessage& other);
    virtual BeaconMessage *dup() const override {return new BeaconMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHostID() const;
    virtual void setHostID(int hostID);

    virtual const ::veins::LAddress::L2Type& getSenderAddress() const;
    virtual ::veins::LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<::veins::LAddress::L2Type&>(const_cast<BeaconMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const ::veins::LAddress::L2Type& senderAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BeaconMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BeaconMessage& obj) {obj.parsimUnpack(b);}


}  // namespace task_offloading


namespace omnetpp {

template<> inline task_offloading::BeaconMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<task_offloading::BeaconMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASK_OFFLOADING_BEACONMESSAGE_M_H

