//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/HelpMessage.msg.
//

#ifndef __TIROCINIO_HELPMESSAGE_M_H
#define __TIROCINIO_HELPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace tirocinio {

class HelpMessage;

}  // namespace tirocinio

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace tirocinio {

/**
 * Class generated from <tt>app/messages/HelpMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet HelpMessage extends veins::BaseFrame1609_4
 * {
 *     int vehicleIndex;
 * }
 * </pre>
 */
class HelpMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int vehicleIndex = 0;

  private:
    void copy(const HelpMessage& other);

  protected:
    bool operator==(const HelpMessage&) = delete;

  public:
    HelpMessage(const char *name=nullptr, short kind=0);
    HelpMessage(const HelpMessage& other);
    virtual ~HelpMessage();
    HelpMessage& operator=(const HelpMessage& other);
    virtual HelpMessage *dup() const override {return new HelpMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getVehicleIndex() const;
    virtual void setVehicleIndex(int vehicleIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HelpMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HelpMessage& obj) {obj.parsimUnpack(b);}


}  // namespace tirocinio


namespace omnetpp {

template<> inline tirocinio::HelpMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<tirocinio::HelpMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TIROCINIO_HELPMESSAGE_M_H

