//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/LoadBalanceTimerMessage.msg.
//

#ifndef __TIROCINIO_LOADBALANCETIMERMESSAGE_M_H
#define __TIROCINIO_LOADBALANCETIMERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace tirocinio {

class LoadBalanceTimerMessage;

}  // namespace tirocinio

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace tirocinio {

/**
 * Class generated from <tt>app/messages/LoadBalanceTimerMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet LoadBalanceTimerMessage extends veins::BaseFrame1609_4
 * {
 *     simtime_t simulationTime;
 * }
 * </pre>
 */
class LoadBalanceTimerMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::simtime_t simulationTime = SIMTIME_ZERO;

  private:
    void copy(const LoadBalanceTimerMessage& other);

  protected:
    bool operator==(const LoadBalanceTimerMessage&) = delete;

  public:
    LoadBalanceTimerMessage(const char *name=nullptr, short kind=0);
    LoadBalanceTimerMessage(const LoadBalanceTimerMessage& other);
    virtual ~LoadBalanceTimerMessage();
    LoadBalanceTimerMessage& operator=(const LoadBalanceTimerMessage& other);
    virtual LoadBalanceTimerMessage *dup() const override {return new LoadBalanceTimerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getSimulationTime() const;
    virtual void setSimulationTime(::omnetpp::simtime_t simulationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LoadBalanceTimerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LoadBalanceTimerMessage& obj) {obj.parsimUnpack(b);}


}  // namespace tirocinio


namespace omnetpp {

template<> inline tirocinio::LoadBalanceTimerMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<tirocinio::LoadBalanceTimerMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TIROCINIO_LOADBALANCETIMERMESSAGE_M_H

