//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/LoadBalancingMessage.msg.
//

#ifndef __TIROCINIO_LOADBALANCINGMESSAGE_M_H
#define __TIROCINIO_LOADBALANCINGMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace tirocinio {

class LoadBalancingMessage;

}  // namespace tirocinio

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace tirocinio {

/**
 * Class generated from <tt>app/messages/LoadBalancingMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet LoadBalancingMessage extends veins::BaseFrame1609_4
 * {
 *     string time;
 * }
 * </pre>
 */
class LoadBalancingMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string time;

  private:
    void copy(const LoadBalancingMessage& other);

  protected:
    bool operator==(const LoadBalancingMessage&) = delete;

  public:
    LoadBalancingMessage(const char *name=nullptr, short kind=0);
    LoadBalancingMessage(const LoadBalancingMessage& other);
    virtual ~LoadBalancingMessage();
    LoadBalancingMessage& operator=(const LoadBalancingMessage& other);
    virtual LoadBalancingMessage *dup() const override {return new LoadBalancingMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getTime() const;
    virtual void setTime(const char * time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LoadBalancingMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LoadBalancingMessage& obj) {obj.parsimUnpack(b);}


}  // namespace tirocinio


namespace omnetpp {

template<> inline tirocinio::LoadBalancingMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<tirocinio::LoadBalancingMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TIROCINIO_LOADBALANCINGMESSAGE_M_H

