//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/OkMessage.msg.
//

#ifndef __TASK_OFFLOADING_OKMESSAGE_M_H
#define __TASK_OFFLOADING_OKMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace task_offloading {

class OkMessage;

}  // namespace task_offloading

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace task_offloading {

/**
 * Class generated from <tt>app/messages/OkMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet OkMessage extends veins::BaseFrame1609_4
 * {
 *     int hostID;
 *     string index;
 *     double availableLoad;
 *     double cpuFreq;
 *     veins::LAddress::L2Type senderAddress = -1;
 *     double vehicleAngle;
 * }
 * </pre>
 */
class OkMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int hostID = 0;
    ::omnetpp::opp_string index;
    double availableLoad = 0;
    double cpuFreq = 0;
    ::veins::LAddress::L2Type senderAddress = -1;
    double vehicleAngle = 0;

  private:
    void copy(const OkMessage& other);

  protected:
    bool operator==(const OkMessage&) = delete;

  public:
    OkMessage(const char *name=nullptr, short kind=0);
    OkMessage(const OkMessage& other);
    virtual ~OkMessage();
    OkMessage& operator=(const OkMessage& other);
    virtual OkMessage *dup() const override {return new OkMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHostID() const;
    virtual void setHostID(int hostID);

    virtual const char * getIndex() const;
    virtual void setIndex(const char * index);

    virtual double getAvailableLoad() const;
    virtual void setAvailableLoad(double availableLoad);

    virtual double getCpuFreq() const;
    virtual void setCpuFreq(double cpuFreq);

    virtual const ::veins::LAddress::L2Type& getSenderAddress() const;
    virtual ::veins::LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<::veins::LAddress::L2Type&>(const_cast<OkMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const ::veins::LAddress::L2Type& senderAddress);

    virtual double getVehicleAngle() const;
    virtual void setVehicleAngle(double vehicleAngle);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const OkMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, OkMessage& obj) {obj.parsimUnpack(b);}


}  // namespace task_offloading


namespace omnetpp {

template<> inline task_offloading::OkMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<task_offloading::OkMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASK_OFFLOADING_OKMESSAGE_M_H

