//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/ResponseMessage.msg.
//

#ifndef __TIROCINIO_RESPONSEMESSAGE_M_H
#define __TIROCINIO_RESPONSEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace tirocinio {

class ResponseMessage;

}  // namespace tirocinio

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace tirocinio {

/**
 * Class generated from <tt>app/messages/ResponseMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * packet ResponseMessage extends veins::BaseFrame1609_4
 * {
 *     int hostIndex;
 * }
 * </pre>
 */
class ResponseMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int hostIndex = 0;

  private:
    void copy(const ResponseMessage& other);

  protected:
    bool operator==(const ResponseMessage&) = delete;

  public:
    ResponseMessage(const char *name=nullptr, short kind=0);
    ResponseMessage(const ResponseMessage& other);
    virtual ~ResponseMessage();
    ResponseMessage& operator=(const ResponseMessage& other);
    virtual ResponseMessage *dup() const override {return new ResponseMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHostIndex() const;
    virtual void setHostIndex(int hostIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ResponseMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ResponseMessage& obj) {obj.parsimUnpack(b);}


}  // namespace tirocinio


namespace omnetpp {

template<> inline tirocinio::ResponseMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<tirocinio::ResponseMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TIROCINIO_RESPONSEMESSAGE_M_H

