//
// Generated file, do not edit! Created by opp_msgtool 6.0 from app/messages/TotalComputationTimerMessage.msg.
//

#ifndef __TASK_OFFLOADING_TOTALCOMPUTATIONTIMERMESSAGE_M_H
#define __TASK_OFFLOADING_TOTALCOMPUTATIONTIMERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace task_offloading {

class TotalComputationTimerMessage;

}  // namespace task_offloading

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace task_offloading {

/**
 * Class generated from <tt>app/messages/TotalComputationTimerMessage.msg:22</tt> by opp_msgtool.
 * <pre>
 * message TotalComputationTimerMessage extends cMessage
 * {
 *     int taskId;
 * }
 * </pre>
 */
class TotalComputationTimerMessage : public ::omnetpp::cMessage
{
  protected:
    int taskId = 0;

  private:
    void copy(const TotalComputationTimerMessage& other);

  protected:
    bool operator==(const TotalComputationTimerMessage&) = delete;

  public:
    TotalComputationTimerMessage(const char *name=nullptr, short kind=0);
    TotalComputationTimerMessage(const TotalComputationTimerMessage& other);
    virtual ~TotalComputationTimerMessage();
    TotalComputationTimerMessage& operator=(const TotalComputationTimerMessage& other);
    virtual TotalComputationTimerMessage *dup() const override {return new TotalComputationTimerMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getTaskId() const;
    virtual void setTaskId(int taskId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TotalComputationTimerMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TotalComputationTimerMessage& obj) {obj.parsimUnpack(b);}


}  // namespace task_offloading


namespace omnetpp {

template<> inline task_offloading::TotalComputationTimerMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<task_offloading::TotalComputationTimerMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __TASK_OFFLOADING_TOTALCOMPUTATIONTIMERMESSAGE_M_H

